extends: .github
queue_rules:
  - name: default
    update_method: merge
    allow_queue_branch_edit: true
    queue_branch_merge_method: fast-forward
    queue_conditions:
      - and:
          - check-success = CodeFactor
          - check-success = GitGuardian Security Checks
          - check-success = CodeQL
    autoqueue: true
