extends: .github
queue_rules:
  - name: default
    update_method: merge
    allow_queue_branch_edit: true
    queue_conditions:
      - and:
          - check-success = CodeFactor
          - check-success = GitGuardian Security Checks
          - check-success = CodeQL
          - check-success = Test
    autoqueue: true
    merge_method: fast-forward
merge_protections_settings:
  reporting_method: check-runs
