extends: .github
pull_request_rules:
  - name: Automatically queue Github Actions Updates
    conditions:
      - files ~= action.yaml
      - author = renovate[bot]
    actions:
      queue:
      label:
        add:
          - github-actions
queue_rules:
  - name: default
    update_method: merge
    allow_queue_branch_edit: true
    queue_branch_merge_method: fast-forward
    queue_conditions:
      - and:
          - 'check-success = DeepSource: Secrets'
          - check-success = CodeFactor
          - check-success = GitGuardian Security Checks
          - check-success = CodeQL
