name: OpenCode Tool
description: Run OpenCode to assist with code generation and improvements
inputs:
  opencode_model:
    description: Opencode model to use
    required: false
    default: 'opencode/grok-code'
  opencode_api_key:
    description: Opencode API key
    required: true
runs:
  using: composite
  steps:
    - name: Run opencode
      uses: sst/opencode/github@de2bc25677b419d2af0da8b6a24a05d3f22b67a8 # v1.2.14
      env:
        OPENCODE_API_KEY: ${{ inputs.opencode_api_key }}
      with:
        model: ${{ inputs.opencode_model }}
