name: OpenCode Tool
description: Run OpenCode to assist with code generation and improvements
inputs:
  opencode_model:
    description: Opencode model to use
    required: false
    default: 'opencode/grok-code'
  opencode_api_key:
    description: Opencode API key
    required: true
runs:
  using: composite
  steps:
    - name: Run opencode
      uses: sst/opencode/github@ac018e3a35fe75b57d55ae349a91624609e11448 # v1.1.63
      env:
        OPENCODE_API_KEY: ${{ inputs.opencode_api_key }}
      with:
        model: ${{ inputs.opencode_model }}
