name: OpenCode Tool
description: Run OpenCode to assist with code generation and improvements
inputs:
  opencode_model:
    description: Opencode model to use
    required: false
    default: 'opencode/grok-code'
  opencode_api_key:
    description: Opencode API key
    required: true
runs:
  using: composite
  steps:
    - name: Run opencode
      uses: sst/opencode/github@296250f1b7e1ec992a3a33bee999f5e09a1697d0 # v1.2.10
      env:
        OPENCODE_API_KEY: ${{ inputs.opencode_api_key }}
      with:
        model: ${{ inputs.opencode_model }}
