name: Setup Devenv
description: Setup Devenv Environment
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
    - name: Cache
      uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
      shell: bash
