name: Helpr Action
description: Helpr Action is a GitHub Action that helps AlphaSphere.AI team.
branding:
  icon: help-circle
  color: purple
inputs:
  build_container:
    required: false
    description: Build Container
    default: 'false'
  build_python:
    required: false
    description: Build Python Package
    default: 'false'
  ci_tools:
    required: false
    description: Install CI Tools
    default: 'false'
  lint:
    required: false
    description: Lint Code
    default: 'false'
  release:
    required: false
    description: Release Mode
    default: 'false'
  test:
    required: false
    description: Test Code
    default: 'false'
  version:
    required: false
    description: Bump Version
    default: 'false'
  is_test:
    required: true
    description: Test Mode
  registry:
    required: false
    description: Registry
  install_source:
    required: false
    description: Source to install from (e.g., PyPI Package or Git source)
  github_token:
    required: false
    description: GitHub Token
  opencode_enabled:
    description: Enable opencode tool
    required: false
    default: 'false'
  uv_lock_sync_enabled:
    description: Enable uv lock sync
    required: false
    default: 'false'
  opencode_model:
    description: Opencode model to use
    required: false
    default: 'opencode/grok-code'
  linter:
    description: Linter to use
    required: false
runs:
  using: composite
  steps:
    - name: Checkout Helpr repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        token: ${{ inputs.github_token }}
        repository: AlphaSphereDotAI/helpr_action
        path: ${{ github.workspace }}
        sparse-checkout: |
          devenv.yaml
          devenv.nix
          devenv.lock
          .envrc
          .gitignore
        sparse-checkout-cone-mode: false
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        token: ${{ inputs.github_token }}
        fetch-depth: 0
        path: ${{ github.workspace }}/repo
    - name: Remove .git directory from Helpr repo
      run: rm -rd ${{ github.workspace }}/.git
      shell: bash
    - name: Check /repo has devenv files
      id: check_devenv_files
      run: |
        if [ ! -f "./repo/devenv.yaml" ]; then
          echo "devenv.yaml not found in the repository root."
          exit 1
        fi
        echo "Devenv files found."
        exit 0
      shell: bash
    - name: Update devenv imports
      if: ${{ steps.check_devenv_files.outcome == 'success' }}
      uses: mikefarah/yq@065b200af9851db0d5132f50bc10b1406ea5c0a8 # v4.50.1
      with:
        cmd: yq -iroy '.imports = ["./repo"]' devenv.yaml
    - name: Setup Devenv
      uses: AlphaSphereDotAI/helpr_action/ci/setup/devenv@67754c4a412bdfcafc7a0f4965c4c9e5952a689b # v0.0.5
    - run: ls -lah
      shell: bash
    - name: Build Container
      uses: AlphaSphereDotAI/helpr_action/ci/build/container@67754c4a412bdfcafc7a0f4965c4c9e5952a689b # v0.0.5
      if: ${{ inputs.build_container == 'true' }}
      with:
        is_test: ${{ inputs.is_test }}
        registry: ${{ inputs.registry }}
        install_source: ${{ inputs.install_source }}
    - name: Build Python Package
      uses: AlphaSphereDotAI/helpr_action/ci/build/python@67754c4a412bdfcafc7a0f4965c4c9e5952a689b # v0.0.5
      if: ${{ inputs.build_python == 'true' }}
    - name: CI Tools
      uses: AlphaSphereDotAI/helpr_action/ci/tools@67754c4a412bdfcafc7a0f4965c4c9e5952a689b # v0.0.5
      if: ${{ inputs.ci_tools == 'true' }}
      with:
        opencode_enabled: ${{ inputs.opencode_enabled }}
        uv_lock_sync_enabled: ${{ inputs.uv_lock_sync_enabled }}
        opencode_model: ${{ inputs.opencode_model }}
    - name: Lint Code
      uses: AlphaSphereDotAI/helpr_action/ci/lint@67754c4a412bdfcafc7a0f4965c4c9e5952a689b # v0.0.5
      if: ${{ inputs.lint == 'true' }}
      with:
        linter: ${{ inputs.linter }}
        github_token: ${{ inputs.github_token }}
    - name: Release Mode
      uses: AlphaSphereDotAI/helpr_action/ci/release@67754c4a412bdfcafc7a0f4965c4c9e5952a689b # v0.0.5
      if: ${{ inputs.release == 'true' }}
    - name: Test Mode
      uses: AlphaSphereDotAI/helpr_action/ci/test@67754c4a412bdfcafc7a0f4965c4c9e5952a689b # v0.0.5
      if: ${{ inputs.test == 'true' }}
    - name: Bump Version
      uses: AlphaSphereDotAI/helpr_action/ci/version@67754c4a412bdfcafc7a0f4965c4c9e5952a689b # v0.0.5
      if: ${{ inputs.version == 'true' }}
