name: Lint
description: Run comprehensive linting and code quality checks
inputs:
  linter:
    description: Linter to use
    required: true
  github_token:
    description: GitHub Token
    required: false
runs:
  using: composite
  steps:
    # Lint
    - name: lint
      if: ${{ inputs.linter == 'lint' }}
      run: devenv tasks run lint
      shell: bash
    # Pre-commit
    - name: Run pre-commit hooks
      if: ${{ inputs.linter == 'pre-commit' }}
      run: devenv test
      shell: bash
    - name: Commit and push applied fixes
      uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
      if: ${{ inputs.linter == 'pre-commit' }}
      with:
        commit_message: "[pre-commit] Apply format fixes"
        commit_options: --no-verify
    # Syft
    - name: SBOM Generation
      uses: anchore/sbom-action@0b82b0b1a22399a1c542d4d656f70cd903571b5c # v0.21.1
      if: ${{ inputs.linter == 'syft' }}
      with:
        path: .
        dependency-snapshot: true
        output-file: ${{ github.event.repository.name }}-sbom.json
        format: syft-json
    # Grype
    - name: Scan current project
      uses: anchore/scan-action@62b74fb7bb810d2c45b1865f47a77655621862a5 # v7.2.3
      if: ${{ inputs.linter == 'grype' }}
      id: scan
      with:
        path: .
        cache-db: true
        output-format: sarif
        output-file: ../results/grype-scan.sarif
    # Trivy repo scan
    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      if: ${{ inputs.linter == 'trivy-repo' }}
      with:
        scan-type: repo
        trivy-config: .github/lint/.trivy.yaml
        format: sarif
        output: ../results/trivy-results-repo.sarif
        github-pat: ${{ inputs.github_token }}
        exit-code: "1"
        scanners: vuln,secret,misconfig,license
    # Trivy config scan
    - name: Run Trivy vulnerability scanner in config mode
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      if: ${{ inputs.linter == 'trivy-config' }}
      with:
        scan-type: config
        trivy-config: .github/lint/.trivy.yaml
        format: sarif
        output: ../results/trivy-results-config.sarif
        exit-code: "1"
        scanners: vuln,secret,misconfig,license
    # Trivy filesystem scan
    - name: Run Trivy vulnerability scanner in filesystem mode
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      if: ${{ inputs.linter == 'trivy-fs' }}
      with:
        scan-type: fs
        trivy-config: .github/lint/.trivy.yaml
        format: github
        output: dependency-results.sbom.json
        exit-code: "1"
        scanners: vuln,secret,misconfig,license
    - name: Upload trivy report as a Github artifact
      if: ${{ (success() || failure()) && inputs.linter == 'trivy-fs' }}
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: trivy-sbom-report
        path: dependency-results.sbom.json
    # DCLint
    - name: Lint Docker Compose file
      uses: docker-compose-linter/dclint-github-action@18659f6a7956706cb67cf9c1ad5e55f4352cbc17 # v1.6.0
      if: ${{ inputs.linter == 'dclint' }}
      with:
        fix: true
        recursive: true
    - name: list all files at ../results
      run: ls -lah ../results
      shell: bash
    - name: Upload Scan SARIF reports
      if: ${{ always() && ! cancelled() }}
      uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
