name: Format
description: Format the source code
inputs:
  formater:
    description: Linter to use
    required: true
  github_token:
    description: GitHub Token
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    # YamlFix
    - name: YamlFix
      if: ${{ inputs.formater == 'yamlfix' }}
      run: uvx yamlfix . -e "**/*.lock.yml"
      shell: bash
    # Ruff
    - name: Ruff
      if: ${{ inputs.formater == 'ruff' }}
      uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0
      with:
        args: format --output-format github
    # Taplo
    - name: Taplo
      if: ${{ inputs.formater == 'taplo' }}
      run: taplo format
      shell: bash
    # Commit and push applied fixes
    - name: Commit and push applied formatter fixes
      uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
      with:
        commit_message: "ci: Apply formatter fixes"
        commit_options: --no-verify
