name: Format
description: Format the source code
inputs:
  formater:
    description: Linter to use
    required: true
  github_token:
    description: GitHub Token
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    # YamlFix
    - name: YamlFix
      if: ${{ inputs.formater == 'yamlfix' }}
      run: uvx yamlfix . -e "**/*.lock.yml"
      shell: bash
    # Ruff
    - name: Ruff
      if: ${{ inputs.linter == 'ruff' }}
      uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3.6.1
      with:
        args: format --output-format github
    # Taplo
    - name: Taplo
      if: ${{ inputs.linter == 'taplo' }}
      run: taplo format
      shell: bash
    # Commit and push applied fixes
    - name: Commit and push applied formatter fixes
      uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
      with:
        commit_message: "ci: Apply formatter fixes"
        commit_options: --no-verify
