name: Release
description: Publish Python package to PyPI
inputs:
  tag_name:
    description: Tag name to release
    required: true
  packages_dir:
    description: Directory containing packages to publish
    required: false
    default: "dist/"
runs:
  using: composite
  steps:
    - name: Retrieve release distributions
      uses: robinraju/release-downloader@daf26c55d821e836577a15f77d86ddc078948b05 # v1.12
      with:
        tag: ${{ inputs.tag_name }}
        out-file-path: ${{ inputs.packages_dir }}
        fileName: "*"

    - name: Publish release distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: ${{ inputs.packages_dir }}
