name: CI Tools
description: CI utilities like opencode and uv lock sync
inputs:
  opencode_enabled:
    description: Enable opencode tool
    required: false
    default: "false"
  opencode_model:
    description: Opencode model to use
    required: false
    default: "opencode/grok-code"
  opencode_api_key:
    description: Opencode API key
    required: true
  uv_lock_sync_enabled:
    description: Enable uv lock sync
    required: false
    default: "false"
runs:
  using: composite
  steps:
    # Opencode
    - name: Run opencode
      if: ${{ inputs.opencode_enabled == 'true' }}
      uses: sst/opencode/github@6eb2bdd665b4654521b88c7d82eddc062b1411ed # v1.1.39
      env:
        OPENCODE_API_KEY: ${{ inputs.opencode_api_key }}
      with:
        model: ${{ inputs.opencode_model }}
    # UV Lock Sync
    - name: Sync dependencies and uv.lock
      id: uv_lock
      if: ${{ inputs.uv_lock_sync_enabled == 'true' }}
      run: uv lock
      shell: bash
    - name: Commit and push changes
      if: ${{ steps.uv_lock.outcome == 'success' }}
      uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
      with:
        commit_message: Sync uv.lock
        commit_options: --no-verify
