name: Setup Devenv
description: Setup Devenv Environment
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@4e002c8ec80594ecd40e759629461e26c8abed15 # v31.9.0
    - name: Cache
      uses: cachix/cachix-action@3ba601ff5bbb07c7220846facfa2cd81eeee15a1 # v16
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile install nixpkgs#devenv
      shell: bash
