name: Setup Devenv
description: Setup Devenv Environment
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@616559265b40713947b9c190a8ff4b507b5df49b # v31.10.4
    - name: Cache
      uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
      with:
        name: devenv
    - name: Install devenv.sh
      run: nix profile add nixpkgs#devenv
      shell: bash
