name: Release
description: Publish Python package to PyPI
inputs:
  tag_name:
    description: Tag name to release
    required: true
  packages_dir:
    description: Directory containing packages to publish
    required: false
    default: "dist/"
runs:
  using: composite
  steps:
    - name: Retrieve release distributions
      uses: robinraju/release-downloader@28fc21f50d76778e7023361aa1f863e717d3d56f # v1.13
      with:
        tag: ${{ inputs.tag_name }}
        out-file-path: ${{ inputs.packages_dir }}
        fileName: "*"
    - name: Publish release distributions to PyPI
      uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # release/v1
      with:
        packages-dir: ${{ inputs.packages_dir }}
