name: Lint
description: Checks for source code quality and vulnerabilities
inputs:
  linter:
    description: Linter to use
    required: true
  github_token:
    description: GitHub Token
    required: false
    default: ${{ github.token }}
runs:
  using: composite
  steps:
    # ActionLint
    - name: ActionLint
      if: ${{ inputs.linter == 'actionlint' }}
      run: |-
        ACTIONLINT_MATCHER_URL="https://raw.githubusercontent.com/rhysd/actionlint/main/.github/actionlint-matcher.json"
        curl -fsSL "$ACTIONLINT_MATCHER_URL" -o .github/actionlint-matcher.json
        echo "::add-matcher::.github/actionlint-matcher.json"
        actionlint -color
      shell: bash
    # Hadolint
    - name: Hadolint
      if: ${{ inputs.linter == 'hadolint' }}
      uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
      with:
        format: sarif
        output-file: ../results/hadolint.sarif
    # MarkdownLint
    - name: Lint Markdown files
      uses: DavidAnson/markdownlint-cli2-action@ce4853d43830c74c1753b39f3cf40f71c2031eb9 # v23.0.0
      if: ${{ inputs.linter == 'markdownlint' }}
      with:
        globs: "**/*.md"
        fix: true
    # Ty
    - name: Ty
      if: ${{ inputs.linter == 'ty' }}
      run: ty check --output-format github
      shell: bash
    # YamlLint
    - name: YamlLint
      if: ${{ inputs.linter == 'yamllint' }}
      run: yamllint . --format github
      shell: bash
    # Ruff
    - name: Ruff
      if: ${{ inputs.linter == 'ruff' }}
      uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6 # v3.6.1
      with:
        args: check --output-format sarif --output-file ../results/ruff.sarif
    # ls-lint
    - name: Lint file names
      if: ${{ inputs.linter == 'ls_lint' }}
      uses: ls-lint/action@02e380fe8733d499cbfc9e22276de5085508a5bd # v2.3.1
    # UV Lock Check
    - name: UV Lock Check
      if: ${{ inputs.linter == 'uv_lock_check' }}
      run: uv lock --check
      shell: bash
    # TruffleHog
    - name: TruffleHog
      if: ${{ inputs.linter == 'trufflehog' }}
      run: >-
        trufflehog git ${{github.event.repository.html_url}}
        --branch=${{github.head_ref||github.ref_name}} --fail --github-actions
        --results=verified,unknown --log-level=4
        --no-update
      shell: bash
    # Taplo
    - name: Taplo
      if: ${{ inputs.linter == 'taplo' }}
      run: taplo lint --default-schema-catalogs
      shell: bash
    # Lint
    - name: lint
      if: ${{ inputs.linter == 'lint' }}
      run: devenv tasks run lint
      shell: bash
    # Pre-commit
    - name: Run pre-commit hooks
      if: ${{ inputs.linter == 'pre-commit' }}
      run: devenv test
      shell: bash
    - name: Commit and push applied fixes
      uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
      if: ${{ inputs.linter == 'pre-commit' }}
      with:
        commit_message: "[pre-commit] Apply format fixes"
        commit_options: --no-verify
    # Syft
    - name: SBOM Generation
      uses: anchore/sbom-action@deef08a0db64bfad603422135db61477b16cef56 # v0.22.1
      if: ${{ inputs.linter == 'syft' }}
      with:
        path: .
        dependency-snapshot: true
        output-file: ${{ github.event.repository.name }}-sbom.json
        format: syft-json
    # Grype
    - name: Scan current project
      uses: anchore/scan-action@e1165082ffb1fe366ebaf02d8526e7c4989ea9d2 # v7.4.0
      if: ${{ inputs.linter == 'grype' }}
      with:
        path: .
        cache-db: true
        output-format: sarif
        output-file: ../results/grype-scan.sarif
    # Trivy repo scan
    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      if: ${{ inputs.linter == 'trivy-repo' }}
      with:
        scan-type: repo
        trivy-config: .github/lint/.trivy.yaml
        format: sarif
        output: ../results/trivy-results-repo.sarif
        github-pat: ${{ inputs.github_token }}
        exit-code: "1"
        scanners: vuln,secret,misconfig,license
    # Trivy config scan
    - name: Run Trivy vulnerability scanner in config mode
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      if: ${{ inputs.linter == 'trivy-config' }}
      with:
        scan-type: config
        trivy-config: .github/lint/.trivy.yaml
        format: sarif
        output: ../results/trivy-results-config.sarif
        github-pat: ${{ inputs.github_token }}
        exit-code: "1"
        scanners: vuln,secret,misconfig
    # Trivy filesystem scan
    - name: Run Trivy vulnerability scanner in filesystem mode
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      if: ${{ inputs.linter == 'trivy-fs' }}
      with:
        scan-type: fs
        trivy-config: .github/lint/.trivy.yaml
        format: github
        output: dependency-results.sbom.json
        github-pat: ${{ inputs.github_token }}
        exit-code: "1"
        scanners: vuln,secret,misconfig
    - name: Upload trivy report as a Github artifact
      if: ${{ (success() || failure()) && inputs.linter == 'trivy-fs' }}
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: trivy-sbom-report
        path: dependency-results.sbom.json
    # DCLint
    - name: Lint Docker Compose file
      uses: docker-compose-linter/dclint-github-action@18659f6a7956706cb67cf9c1ad5e55f4352cbc17 # v1.6.0
      if: ${{ inputs.linter == 'dclint' }}
      with:
        fix: true
        recursive: true
    - name: list all files at ../results
      run: ls -lah ../results
      shell: bash
    # Upload SARIF
    - name: Upload Scan SARIF reports
      if: ${{ always() && ! cancelled() }}
      uses: github/codeql-action/upload-sarif@b20883b0cd1f46c72ae0ba6d1090936928f9fa30 # v4.32.0
    # Report
    - name: Job Summary
      uses: jazanne/job-summary-action@690eb386a0b86fe4da7c6f0e543e61330ff09f06 # v1.0.0
      if: success() || failure()
      with:
        summary: |-
          ## UV Lock Check
          - **Status**: ${{ steps.uv_lock_check.outcome == 'success' && ':white_check_mark:' || ':x:' }}
