name: Version
description: Automated version bumping and tagging
inputs:
  bump_type:
    description: Type of version bump (patch, minor, major)
    required: false
    default: "patch"
outputs:
  new_version:
    description: The new version after bumping
    value: ${{ steps.get_package_version.outputs.result }}
runs:
  using: composite
  steps:
    - name: Increase the version
      run: uv version --bump ${{ inputs.bump_type }}
      shell: bash
    - name: Get Package version
      id: get_package_version
      run: echo "result=$(uv version --short)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Tag updated version
      uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
      with:
        commit_message: "Tag: ${{ steps.get_package_version.outputs.result }}"
        tagging_message: ${{ steps.get_package_version.outputs.result }}
