name: Release
description: Publish Release
inputs:
  tag_name:
    description: Tag name to release
    required: true
  packages_dir:
    description: Directory containing packages to publish
    required: false
    default: "dist/"
  registry:
    description: Registry to publish to
    required: true
runs:
  using: composite
  steps:
    - name: Publish release distributions to PyPI
      uses: AlphaSphereDotAI/helpr_action/ci/release/pypi@92aa4bc49cea095d9fd6ed0f1c172b63f9193b6d # v0.0.58
      if: ${{ inputs.registry == 'pypi' }}
      with:
        tag_name: ${{ inputs.tag_name }}
        packages_dir: ${{ inputs.packages_dir }}
