name: Release
description: Publish Release
inputs:
  tag_name:
    description: Tag name to release
    required: true
  packages_dir:
    description: Directory containing packages to publish
    required: false
    default: "dist/"
  registry:
    description: Registry to publish to
    required: true
runs:
  using: composite
  steps:
    - name: Publish release distributions to PyPI
      uses: AlphaSphereDotAI/helpr_action/ci/release/pypi@21729a6d31f625f3a3c66d7fde2c54037e2cd67b # v0.0.53
      if: ${{ inputs.registry == 'pypi' }}
      with:
        tag_name: ${{ inputs.tag_name }}
        packages_dir: ${{ inputs.packages_dir }}
