name: Release
description: Publish Release
inputs:
  tag_name:
    description: Tag name to release
    required: true
  packages_dir:
    description: Directory containing packages to publish
    required: false
    default: 'dist/'
  registry:
    description: Registry to publish to
    required: true
runs:
  using: composite
  steps:
    - name: Publish release distributions to PyPI
      uses: AlphaSphereDotAI/helpr_action/ci/release/pypi@21917b19e8ec7232117c53efd0263632b87734c0 # v0.0.37
      if: ${{ inputs.registry == 'pypi' }}
      with:
        tag_name: ${{ inputs.tag_name }}
        packages_dir: ${{ inputs.packages_dir }}
