name: Lint
description: Run comprehensive linting and code quality checks
inputs:
  linter:
    description: Linter to use
    required: true
runs:
  using: composite
  steps:
    # Taplo lint
    - name: Taplo lint
      if: ${{ inputs.linter == 'taplo' }}
      run: devenv shell taplo-lint
      shell: bash

    # TruffleHog
    - name: Git Secret Scanning
      if: ${{ inputs.linter == 'trufflehog' }}
      run: >-
        devenv shell trufflehog git ${{github.event.repository.html_url}}
        --branch=${{github.head_ref || github.ref_name}}
        --fail --github-actions --results=verified,unknown --log-level=4 --no-update
      shell: bash

    # Pre-commit
    - name: Run pre-commit hooks
      if: ${{ inputs.linter == 'pre-commit' }}
      run: devenv test
      shell: bash
    - name: Commit and push applied fixes
      uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
      with:
        commit_message: "[pre-commit] Apply format fixes"
        commit_options: --no-verify

    # UV Lock Check
    - name: Check if the lockfile is up-to-date
      if: ${{ inputs.linter == 'uv-lock' }}
      id: uv_lock_check
      run: devenv shell uv_lock_check
      shell: bash
    - name: Job Summary
      uses: jazanne/job-summary-action@690eb386a0b86fe4da7c6f0e543e61330ff09f06 # v1.0.0
      if: success() || failure()
      with:
        summary: |
          ## UV Lock Check
          - **Status**: ${{ steps.uv_lock_check.outcome == 'success' && ':white_check_mark:' || ':x:' }}

    # ls-lint
    - name: Lint file names
      if: ${{ inputs.linter == 'ls-lint' }}
      run: devenv shell ls-lint-check
      shell: bash

    # Ruff check
    - name: Ruff check
      run: devenv shell ruff-check
      shell: bash
    - name: upload Ruff scan SARIF report
      if: success() || failure()
      uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
      with:
        sarif_file: ruff.sarif

    # Ruff format
    - name: Ruff format
      uses: astral-sh/ruff-action@57714a7c8a2e59f32539362ba31877a1957dded1 # v3.5.1
      with:
        args: format --config .github/lint/.ruff.toml --output-format github
    - name: Commit and push applied Ruff fixes
      uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
      with:
        commit_message: "[Ruff] Apply format fixes"
        commit_options: --no-verify

    # YamlFix
    - name: Format
      run: uvx yamlfix . --config-file .github/lint/.yamlfix.toml
      shell: bash
    - name: Commit and push applied linter fixes
      uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
      with:
        commit_message: "[YamlFix] Apply linters fixes"
        commit_options: --no-verify

    # YamlLint
    - name: Check
      run: uvx yamllint . --strict -c=.github/lint/.yamllint.yaml --format github
      shell: bash

    # Syft
    - name: SBOM Generation
      uses: anchore/sbom-action@0b82b0b1a22399a1c542d4d656f70cd903571b5c # v0.21.1
      with:
        path: .
        dependency-snapshot: true
        output-file: ${{ github.event.repository.name }}-sbom.json
        format: syft-json

    # Grype
    - name: Scan current project
      uses: anchore/scan-action@62b74fb7bb810d2c45b1865f47a77655621862a5 # v7.2.3
      id: scan
      with:
        path: .
        cache-db: true
    - name: upload Anchore scan SARIF report
      if: success() || failure()
      uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}

    # Trivy repo scan
    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      with:
        scan-type: repo
        trivy-config: .github/lint/.trivy.yaml
        format: sarif
        output: trivy-results-repo.sarif
        github-pat: ${{ secrets.GH_TOKEN }}
        exit-code: "1"
        scanners: vuln,secret,misconfig,license
    - name: Upload Trivy repo scan results to GitHub Security tab
      if: success() || failure()
      uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
      with:
        sarif_file: trivy-results-repo.sarif
        category: repo

    # Trivy config scan
    - name: Run Trivy vulnerability scanner in config mode
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      with:
        scan-type: config
        trivy-config: .github/lint/.trivy.yaml
        format: sarif
        output: trivy-results-config.sarif
        exit-code: "1"
        scanners: vuln,secret,misconfig,license
    - name: Upload Trivy config scan results to GitHub Security tab
      if: success() || failure()
      uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
      with:
        sarif_file: trivy-results-config.sarif
        category: config

    # Trivy filesystem scan
    - name: Run Trivy vulnerability scanner in filesystem mode
      uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
      with:
        scan-type: fs
        trivy-config: .github/lint/.trivy.yaml
        format: github
        output: dependency-results.sbom.json
        exit-code: "1"
        scanners: vuln,secret,misconfig,license
    - name: Upload trivy report as a Github artifact
      if: success() || failure()
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: trivy-sbom-report
        path: dependency-results.sbom.json

    # DCLint
    - name: Lint Docker Compose file
      uses: docker-compose-linter/dclint-github-action@18659f6a7956706cb67cf9c1ad5e55f4352cbc17 # v1.6.0
      with:
        fix: true
        recursive: true

    # Ty
    - name: Check
      run: uvx ty check --output-format github
      shell: bash

    # MarkdownLint
    - name: Lint Markdown files
      uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101 # v22.0.0
      with:
        globs: "**/*.md"
        config: .github/lint/.markdownlint.yaml
        fix: true

    # Hadolint
    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5 # v3.3.0
      with:
        config: .github/lint/.hadolint.yaml
        format: sarif
        output-file: hadolint.sarif
    - name: upload Hadolint scan SARIF report
      if: success() || failure()
      uses: github/codeql-action/upload-sarif@cdefb33c0f6224e58673d9004f47f7cb3e328b89 # v4.31.10
      with:
        sarif_file: hadolint.sarif

    # ActionLint
    - name: Install actionlint
      uses: jaxxstorm/action-install-gh-release@6096f2a2bbfee498ced520b6922ac2c06e990ed2 # v2.1.0
      with:
        repo: rhysd/actionlint
        cache: enable
    - name: Download actionlint-matcher.json
      run: >-
        curl -fsSL https://raw.githubusercontent.com/rhysd/actionlint/main/.github/actionlint-matcher.json
        -o .github/actionlint-matcher.json
      shell: bash
    - name: Run actionlint
      run: |-
        echo "::add-matcher::.github/actionlint-matcher.json"
        actionlint -color
      shell: bash
