name: Version
description: Automated version bumping and tagging
inputs:
  bump_type:
    description: Type of version bump (patch, minor, major)
    required: false
    default: "patch"
  commit_changes:
    description: Whether to commit version changes
    required: false
    default: "true"
  create_tag:
    description: Whether to create a git tag
    required: false
    default: "true"
outputs:
  new_version:
    description: The new version after bumping
    value: ${{ steps.get_package_version.outputs.result }}
runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0
      with:
        enable-cache: true
        activate-environment: true

    - name: Increase the version
      run: uv version --bump ${{ inputs.bump_type }}
      shell: bash

    - name: Get Package version from pyproject.toml
      id: get_package_version
      uses: mikefarah/yq@065b200af9851db0d5132f50bc10b1406ea5c0a8 # v4.50.1
      with:
        cmd: yq -roy '.project.version' pyproject.toml

    - name: Commit updated version
      if: ${{ inputs.commit_changes == 'true' }}
      uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
      with:
        commit_message: "Tag: ${{ steps.get_package_version.outputs.result }}"
        tagging_message: ${{ steps.get_package_version.outputs.result }}

    - name: Create tag manually
      if: ${{ inputs.create_tag == 'true' && inputs.commit_changes == 'false' }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pyproject.toml
        git commit -m "Tag: ${{ steps.get_package_version.outputs.result }}"
        git tag ${{ steps.get_package_version.outputs.result }}
        git push origin main
        git push origin ${{ steps.get_package_version.outputs.result }}
      shell: bash
