name: Test
description: Test the project codebase
inputs:
  test_code:
    description: Test Code
    required: true
  test_container:
    description: Test Container
    required: true
  test_dependency_compatibility:
    description: Test Dependency Compatibility
    required: true
  dependency_compatibility_tool:
    description: Tool to use for dependency compatibility check
    required: true
  image_tag:
    description: Image Tag
    required: false
  github_token:
    description: GitHub Token
    required: false
    default: ${{ github.token }}
  linter:
    description: Linter to use
    required: false
runs:
  using: composite
  steps:
    - name: Test Dependency Compatibility
      uses: AlphaSphereDotAI/helpr_action/ci/testing/dependency_compatibility@437cc35f2d11ac49ce625af149068151e9544fff # v0.0.66
      if: ${{ inputs.test_dependency_compatibility == 'true' }}
      with:
        tool: ${{ inputs.dependency_compatibility_tool }}
    - name: Test code
      uses: AlphaSphereDotAI/helpr_action/ci/testing/code@437cc35f2d11ac49ce625af149068151e9544fff # v0.0.66
      if: ${{ inputs.test_code == 'true' }}
      with:
        linter: ${{ inputs.linter }}
        github_token: ${{ inputs.github_token }}
    - name: Test Container Image
      uses: AlphaSphereDotAI/helpr_action/ci/testing/container@437cc35f2d11ac49ce625af149068151e9544fff # v0.0.66
      if: ${{ inputs.test_container == 'true' }}
      with:
        image_tag: ${{ inputs.image_tag }}
        github_token: ${{ inputs.github_token }}
