name: Dependency Compatibility Test
description: Test the project dependency compatibility
inputs:
  tool:
    description: Tool to use for dependency compatibility check
    required: true
  shell:
    description: Shell to use
    default: bash
runs:
  using: composite
  steps:
    - name: Test Dependency Compatibility
      uses: AlphaSphereDotAI/helpr_action/ci/testing/dependency_compatibility/uv@c469add08eb4a592178ab87f0854e5e35023c354 # v0.0.70
      if: ${{ inputs.tool == 'uv' }}
      with:
        shell: ${{ inputs.shell }}
