name: Dependency Compatibility Test
description: Test the project dependency compatibility
inputs:
  tool:
    description: Tool to use for dependency compatibility check
    required: true
  shell:
    description: Shell to use
    default: bash
runs:
  using: composite
  steps:
    - name: Test Dependency Compatibility
      uses: AlphaSphereDotAI/helpr_action/ci/testing/dependency_compatibility/uv@f8f10664cca8e9bd8f1cec9baa16aa56ed7e38d4 # v0.0.72
      if: ${{ inputs.tool == 'uv' }}
      with:
        shell: ${{ inputs.shell }}
