name: Dependency Compatibility Test
description: Test the project dependency compatibility
inputs:
  tool:
    description: Tool to use for dependency compatibility check
    required: true
  shell:
    description: Shell to use
    default: bash
runs:
  using: composite
  steps:
    - name: Test Dependency Compatibility
      uses: AlphaSphereDotAI/helpr_action/ci/testing/dependency_compatibility/uv@5f40d1e1b714a0749ad05fc82607f65b309c0e62 # v0.0.66
      if: ${{ inputs.tool == 'uv' }}
      with:
        shell: ${{ inputs.shell }}
